version: "3"
services:
  redis:
    image: redis:6.2.6-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    environment:
      REDIS_PASSWORD: mypassword
      REDIS_DATABASES: 16
      REDIS_MAXMEMORY: 512mb
      REDIS_APPENDONLY: "yes"
volumes:
  redis-data: