name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
   
    - name: Checkout code
      uses: actions/checkout@v2

   
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

   
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1


    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

  
    - name: Install Docker Compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose
        docker-compose --version  # Kiểm tra phiên bản Docker Compose


    - name: Build and Push Docker Images
      run: |
        # Build image từ docker-compose
        docker-compose build

        # Push image lên Docker Hub (thêm tag để dễ quản lý)
        docker-compose push
